# Set the line length limit (standard is 88 or 100)
line-length = 100
target-version = "py313"

[lint]
# Select rules: 
# E (Error), F (Pyflakes), I (Isort - imports), B (Bugbear), UP (Pyupgrade)
select = ["E", "F", "I", "B", "UP"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"